version: "3"

services:
  smart-portal:
    image: smart-portal:latest
    networks:
      - smart-network
    depends_on:
      - smart-home
    ports:
      - "80:8080"
    volumes:
      - data:"/data"
      - log:"/log"
  smart-home:
    image: smart-home:latest
    networks:
      - smart-network
    ports:
      - "9091:9091"
    environment:
      - DATABASE_NAME=smart_home
      - MYSQL_IP=192.168.31.248
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_POD_NAME=mysql-pro
networks:
  smart-network:
    driver: bridge

volumes:
  data:
  log:
