server:
  port: 9091
  #ssl:
  #  enabled: true
  #  key-store: classpath:oauth2.jks
  #  key-alias: oauth2
  #  key-store-type: JKS
  #  key-store-password: 123456
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  flyway:
    locations: classpath:mysql
    enabled: true
    encoding: UTF-8
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validate-on-migrate: true
    baseline-on-migrate: true
  profiles:
    include: base-path
    # 适配多个yml配置文件，多个配置文件以‘,’分割
    active: ${DEPLOYMENT_ENVIRONMENT:prod}
logging:
  config: classpath:log4j2.yml
mybatis-plus:
  global-config:
    banner: false
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources
      - /v1/smart/user/login
      - /v1/smart/user/register
      - /v1/smart/user/info
      - /v1/smart/user/*
      - /v1/smart/role/listAll
      - /v1/smart/*