springdoc:
  api-docs:
    enabled: false
spring:
  flyway:
    locations: classpath:db/mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/${DATABASE_NAME}?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      default-auto-commit: false
      default-read-only: false
      # 初始化大小
      initial-size: 2
      # 最大值
      max-active: 5
      # 最小值
      min-idle: 2
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 18000
      # 配置一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 1200000
      pool-prepared-statements: true
      max-open-prepared-statements: 100
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
      remove-abandoned: true
      remove-abandoned-timeout: 300
      max-wait: 3000
      keep-alive: true
      phy-max-use-count: 2000
